2024-12-08 17:29:46,596 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "D:\UrbanUniversity\Module_12\Logging\tests_12_4.py", line 25, in test_run
    runner = rt_with_exceptions.Runner(False)
  File "D:\UrbanUniversity\Module_12\Logging\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано bool

2024-12-08 17:29:46,597 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "D:\UrbanUniversity\Module_12\Logging\tests_12_4.py", line 14, in test_walk
    runner = rt_with_exceptions.Runner("Alex", -5)
  File "D:\UrbanUniversity\Module_12\Logging\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
